Text($001F6E98, "Disorder")
Text("BGM01\n%3Disorder%1")
Text("Courage of Passing")
Text("BGM02\n%3Courage of Passing%1")
Text("Mind's Eye")
Text("BGM03\n%3Mind's Eye%1")
Text("Head-On Crush")
Text("BGM04\n%3Head-On Crush%1")
Text("Spiritual Trip")
Text("BGM05\n%3Spiritual Journey%1")
Text("Bright Future")
Text("BGM06\n%3Bright Future%1")
Text("Resolution")
Text("BGM07\n%3Resolution%1")
Text("Current Aspect")
Text("BGM08\n%3Current Aspect%1")
Text("Breaking Through")
Text("BGM09\n%3Breaking Through%1")
Text("BGM10\n%3Strain%1")
Text("Solid Steering")
Text("BGM11\n%3Solid Steering%1")
Text("Leap to First")
Text("BGM12\n%3Leap to First%1")
Text("Naughty Chase")
Text("BGM13\n%3Naughty Chase%1")
Text("Throwaway\nOrnament")
Text("BGM14\n%3Throwaway Ornament%1")
Text("Smash the Rival")
Text("BGM15\n%3Smash the Rival%1")
Text("Metamorphosis")
Text("BGM16\n%3Metamorphosis%1")
Text("Conquest")
Text("BGM17\n%3Conquest%1")
Text("Engine Beat")
Text("BGM18\n%3Engine Heartbeat%1")
Text("Sublime Passion")
Text("BGM19\n%3Sublime Passion%1")
Text("Just a Drop\nin the Ocean")
Text("BGM20\n%3Just a Drop\in the Ocean%1")
Text("Head-On Crush (Remix)")
Text("BGM21\n%3Head-On Crush (Remix)%1")
Text("Head-On Crush (Raw Mix)")
Text("BGM22\n%3Head-On Crush (Raw Mix)%1")
Text("Aero Rave")
Text("BGM23\n%3Aero Rave%1")
Text("Practice Battle")
Text("BGM24\n%3Practice Battle%1")
Text("BGM25\n%3Destiny%1")
Text("Soul Twins (Instrumental)")
Text("BGM26\n%3Soul Twins (Instrumental)%1")
Text("Identity Crisis (Instrumental)")
Text("BGM27\n%3Identity Crisis (Instrumental)%1")
Text("Endless Field")
Text("BGM28\n%3Endless Field%1")
Text("Future GPX")
Text("BGM29\n%3Future GPX%1")
Text("Challenger")
Text("BGM30\n%3Challenger%1")
Text("Tamashii")
Text("BGM31\n%3-%1")
Text("BGM32\n%3-%1")
Text("BGM33\n%3-%1")
Text("BGM34\n%3-%1")
Text("Soul Twins")
Text("BGM35\n%3Soul Twins%1")
Text("Identity Crisis")
Text("BGM36\n%3Identity Crisis%1")
Text("Rhythm Red")
Text("BGM37\n%3Rhythm Red%1")
Text("Duet Stars")
Text("BGM38\n%3Duet Stars%1")
Text("Duet Stars (Instrumental)")
Text("BGM39\n%3Duet Stars (Instrumental)%1")
Text("Time Up!")
Text("BGM40\n%3Time Up!%1")
Text("Make Your Move!")
Text("BGM41\n%3Make Your Move!%1")
Text("Field Experience")
Text("BGM42\n%3Field Experience%1")
Text("Curtain Raising")
Text("BGM43\n%3Curtain Raising%1")
Text("Raw Skill")
Text("BGM44\n%3Raw Skill%1")
Text("Parade\n(Part 1)")
Text("BGM45\n%3Parade\n(Part 1)%1")
Text("Kaze ~GPX~")
Text("BGM46\n%3Kaze ~GPX~%1")
Text("Parade\n(Part 2)")
Text("BGM47\n%3Parade\n(Part 2)%1")
Text("GPX Opening 01 (Casual ver.)")
Text("BGM48\n%3GPX Opening 01 (Casual ver.)%1")
Text("GPX Opening 02 (Excite ver.)")
Text("BGM49\n%3GPX Opening 02 (Excite ver.)%1")
Text("GPX Opening 03 (Natural ver.)")
Text("BGM50\n%3GPX Opening 03 (Natural ver.)%1")
Text("GPX Opening 04 (Funky ver.)")
Text("BGM51\n%3GPX Opening 04 (Funky ver.)%1")
Text("GPX Opening 05 (Bright ver.)")
Text("BGM52\n%3GPX Opening 05 (Bright ver.)%1")
