Text($001F9250, "v-Asurada AKF-0\n(Hayato Kazami)\n")
Text("Garland SF-03\n(Hayato Kazami)")
Text("Garland SF-03\n(Henri Claytor)")	
Text("Garland SF-03/G\n(Henri Claytor)\nGIO engine version")
Text("ƒË-Asurada AKF-0/G\n(Hayato Kazami)\nGIO engine version")
Text("Super Asurada AKF-11\n(Hayato Kazami)\nGame original tuning version")
Text("Super Asurada 01\n(Hayato Kazami)\nGame original tuning version")
Text("Super Asurada SA-01/C\n(Hayato Kazami)\nGame original tuning version")
Text("Asurada G.S.X.\n(Hayato Kazami)\nGame original tuning version")
Text("ƒË-Asurada AKF-0\n(Asuka Sugo)\nGame original machine")
Text("Garland SF-03\n(Osamu Sugo)\nGame original machine")
Text("Garland SF-03\n(Clair Fortran)\nGame original machine")
Text("AKF-0/1B Nemesis\n(Seiichiro Shiba)")
Text("AKF-0/1B Nemesis\n(Rena Yuki)\nGame original machine")
Text("Super V8\n(V8)\nGame original machine")
Text("Al-Zard NP-1\n(Bleed Kaga)")
Text("Al-Zard NP-1\n(Phill Fritz)")
Text("Ex-Superion Z/A-10\n(Naoki Shinjyo)")
Text("Ex-Superion Z/A-10\n(Bleed Kaga)")
Text("Ex-Superion Z/A-10\n(Knight Schumacher)\nGame original machine")
Text("Al-Zard NP-1\n(Kyoshiro Nagumo)\nGame original machine")
Text("Ogre AN-21\n(Jotaro Kaga)")
Text("Stihl HG-165\n(Jackie Gudelhian)")
Text("Stihl HG-165\n(Franz Heinel)")
Text("Stihl HG-165\n(Lisa Heinel)\nGame original machine")
Text("Spiegel HP-022\n(Jackie Gudelhian)")
Text("Spiegel HP-022\n(Franz Heinel)\nGame original machine")
Text("Spiegel HP-022\n(Marie Albert Luiza)")
Text("Issuxark 00-X3/II\n(Karl Lichter von Randoll)")
Text("Issuxark 00-X3/II\n(Shinjo Naoki)")
Text("Issuxark 00-X3/II\n(Prince Rosenkreuz)\nGame original machine")
Text("Issuxark 00-X3/II\n(Claude Shinjyo)\nGame original machine")
Text("Strat Missionel MS-3/B\n(Leon Earnhardt)")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)\nGame original machine")
Text("El Condor B-19\n(Carson Nina)")
Text("El Condor B-19\n(Legg Anderson)")
Text("Stampede J-1001\n(Marie Albert Luiza)")
Text("Stampede J-1001\n(Michael Norris)")
Text("Tornado Stag C-1\n(P.F. Nehru)")
Text("Tornado Stag C-1\n(Daniel Elfman)")
Text("Hybrid Koln XZ-01\n(Ennio Cassini)")
Text("Hybrid Koln XZ-01\n(Artois Jobhel)")
Text("Xi-Juggler V/5\n(Alan Brioche)")
Text("Xi-Juggler V/5\n(Rick Brayton)")
Text("Lay-Up P.P.P. 108\n(Bud Leitzinger)")
Text("Lay-Up P.P.P. 108\n(Ross Bellhausen)")
Text("Silent Screamer y-2\n(J.M. Lenz)")
Text("Silent Screamer y-2\n(S. Vitte)")
Text("Counter Arrow T.O.S.X-R\n(Akira Hiyoshi)")
Text("Counter Arrow T.O.S.X-R\n(Cora Foitek)")

//Text("v-Asurada AKF-0\n(Kazami Hayato)\n")
//Text("v-Asurada AKF-0\n(Kazami Hayato)\n")
//Text("Garland SF-03\n(Kazami Hayato)\n")
//Text("Garland SF-03\n(Kazami Hayato)\n")
//Text("Garland SF-03\n(Kazami Hayato)\n")
