Text($001FA008, "\-ASURADA AKF-0 [RED VER.")
Text("ƒË-Asurada AKF-0\n(Hayato Kazami)\n%5Red version%1")
Text("\-ASURADA AKF-0 [GREEN VER.")
Text("ƒË-Asurada AKF-0\n(Hayato Kazami)\n%5Green version%1")
Text("\-ASURADA AKF-0 [BLACK VER.")
Text("ƒË-Asurada AKF-0\n(Hayato Kazami)\n%5Black version%1")
Text("ASURADA AKF-0 [RED VER.")
Text("Garland SF-03\n(Hayato Kazami)\n%5Red version%1")
Text("GARLAND SF-03 [BLACK VER.")
Text("Garland SF-03\n(Hayato Kazami)\n%5Black version%1")
Text("GARLAND SF-03 [PINK VER.")
Text("Garland SF-03\n(Hayato Kazami)\n%5Pink version%1")
Text("Garland SF-03\n(Henri Claytor)\n%5Red version%1")
Text("Garland SF-03\n(Henri Claytor)\n%5Black version%1")
Text("Garland SF-03\n(Henri Claytor)\n%5Pink version%1")
Text("STIL HG-165 [BLUE VER.")
Text("Stihl HG-165\n(Jackie Gudelhian)\n%5Blue version%1")
Text("STIL HG-165 [GREEN VER.")
Text("Stihl HG-165\n(Jackie Gudelhian)\n%5Green version%1")
Text("STIL HG-165 [BLACK VER.")
Text("Stihl HG-165\n(Jackie Gudelhian)\n%5Black version%1")
Text("Stihl HG-165\n(Franz Heinel)\n%5Blue version%1")
Text("Stihl HG-165\n(Franz Heinel)\n%5Green version%1")
Text("Stihl HG-165\n(Franz Heinel)\n%5Black version%1")
Text("ISSUXARK 00-X3/] [BLUE VER.")
Text("Issuxark 00-X3/II\n(Karl Lichter von Randoll)\n%5Blue version%1")
Text("ISSUXARK 00-X3/] [GOLD VER.")
Text("Issuxark 00-X3/II\n(Karl Lichter von Randoll)\n%5Gold version%1")
Text("ISSUXARK 00-X3/] [SILVER VER.")
Text("Issuxark 00-X3/II\n(Karl Lichter von Randoll)\n%5Silver version%1")
Text("Issuxark 00-X3/II\n(Naoki Shinjo)\n%5Blue version%1")
Text("Issuxark 00-X3/II\n(Naoki Shinjo)\n%5Gold version%1")
Text("Issuxark 00-X3/II\n(Naoki Shinjo)\n%5Silver version%1")
Text("AL-ZARD NP-1 [RED VER.")
Text("Al-Zard NP-1\n(Bleed Kaga)\n%5Red version%1")
Text("AL-ZARD NP-1 [VIOLET VER.")
Text("Al-Zard NP-1\n(Bleed Kaga)\n%5Violet version%1")
Text("AL-ZARD NP-1 [BLUE VER.")
Text("Al-Zard NP-1\n(Phill Fritz)\n%Blue version%1")
Text("Al-Zard NP-1\n(Phill Fritz)\n%5Red version%1")
Text("Al-Zard NP-1\n(Phill Fritz)\n%5Violet version%1")
Text("Al-Zard NP-1\n(Phill Fritz)\n%5Blue version%1")
Text("STRAT MISSIONEL MS-3/B [WHITE VER.")
Text("Strat Missionel MS-3/B\n(Leon Earnhardt)\n%5White version%1")
Text("STRAT MISSIONEL MS-3/B [RED VER.")
Text("Strat Missionel MS-3/B\n(Leon Earnhardt)\n%5Red version%1")
Text("STRAT MISSIONEL MS-3/B [BLUE VER.")
Text("Strat Missionel MS-3/B\n(Leon Earnhardt)\n%5Blue version%1")
Text("STRAT MISSIONEL MS-3/B [ WHITE VER.")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)\n%5White version%1")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)\n%5Red version%1")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)\n%5Blue version%1")
Text("EXSSPERION Z/A-10")
Text("Ex-Superion Z/A-10\n(Bleed Kaga)")
Text("Ex-Superion Z/A-10\n(Shinjo Naoki)")
Text("SUPER ASURADA AKF-11 SPECIAL VER.")
Text("Super Asurada AKF-11\n(Hayato Kazami)\n%5Game original tuning version%1")
Text("ASURADA G.S.X SPECIAL VER.")
Text("Asurada G.S.X.\n(Hayato Kazami)\n%5Game original tuning version%1")
Text("SUPER ASURADA 01 SPECIAL VER.")
Text("Super Asurada 01\n(Hayato Kazami)\n%5Game original tuning version%1")
Text("SUPER ASURADA SA-01/C SPECIAL VER.")
Text("Super Asurada SA-01/C\n(Hayato Kazami)\n%5Game original tuning version%1")
Text("SPIEGEL HP-022")
Text("Spiegel HP-022 (Jackie Gudelhian)")
Text("Spiegel HP-022 (Marie Albert Luiza)")
Text("OGRE AN-21")
Text("Ogre AN-21\n(Jotaro Kaga)")
Text("\-ASURADA AKF-0/G")
Text("ƒË-Asurada AKF-0/G\n(Kazami Hayato)\n%5GIO engine version%1")
Text("GARLAND SF-03/G")
Text("Garland SF-03/G\n(Henri Claytor)\n%5GIO engine version%1")
Text("\-ASURADA AKF-0 SPECIAL VER.")
Text("ƒË-Asurada AKF-0\n(Sugo Asuka)\n%5Game original machine%1")
Text("GARLAND SF-03 SPECIAL VER.1")
Text("Garland SF-03\n(Sugo Osamu)\n%5Game original machine%1")
Text("GARLAND SF-03 SPECIAL VER.2")
Text("Garland SF-03\n(Clair Fortran)\n%5Game original machine%1")
Text("AL-ZARD NP-1 SPECIAL VER.")
Text("Al-Zard NP-1\n(Kyoshiro Nagumo)\n%5Game original machine%1")
Text("EXSSPERION Z/A-10 SPECIAL VER.")
Text("Ex-Superion Z/A-10\n(Knight Schumacher)\n%5Game original machine%1")
Text("AKF-0/1B NEMESIS")
Text("AKF-0/1B Nemesis\n(Seiichiro Shiba)")
Text("AKF-0/1B NEMESIS SPECIAL VER.")
Text("AKF-0/1B Nemesis\n(Rena Yuki)\n%5Game original machine%1")
Text("SUPER V8")
Text("Super V8\n(V8)\n%5TGame original machine%1")
Text("STRAT MISSIONEL MS-3/B SPECIAL VER.")
Text("Strat Missionel MS-3/B\n(Edelhi Bootsvorz)\n%5Game original machine%1")
Text("STIL HG-165 SPECIAL VER.")
Text("STIL HG-165\n(Lisa Heinel)\n%5Game original machine%1")
Text("SPIEGEL HP-022 SPECIAL VER.")
Text("SPIEGEL HP-022\n(Franz Heinel)\n%5Game original machine%1")
Text("ISSUXARK 00-X3/] SPECIAL VER.1")
Text("Issuzark 00-X3/II\n(Prince R.)\n%5Game original machine%1")
Text("ISSUXARK 00-X3/] SPECIAL VER.2")
Text("Issuxark 00-X3/II\n(Claude Shinjo)\n%5Game original machine%1")
Text("FUJIOKA")
Text("Fujioka Circuit%1\nDriving License\n%5Drive course in free run%1")
Text("CENTRAL MANHATTAN -R")
Text("Manhattan Island City Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("CAMPO GRANDE -R")
Text("Campo Grande Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("POSTBRIDGE AIRPORT(S) -R")
Text("Postbridge Airport Circuit Short Course (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("CAMPO GRANDE(S) -R")
Text("Campo Grande Circuit Short Course (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("AUGSBURG -R")
Text("Augsburg Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("POSTBRIDGE AIRPORT -R")
Text("Postbridge Airport Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("TOKYO BAY COASTAL -R")
Text("Wangan Special Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("SANMARINO -R")
Text("San Marino Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("HONG KONG CITY -R")
Text("Hong Kong City Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("SYDNEY -R")
Text("Sydney Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("FUJIOKA -R")
Text("Fujioka Circuit (Reverse)\nDriving License\n%5Drive course in free run%1")
Text("XI INTERMEDIATE CUP LICENSE")
Text("%2Survival Match%1\n%5Xi Intermediate Cup%1\nDriving License")
Text("XI INTERMEDIATE CUP #2 LICENSE")
Text("%2Survival Match%1\n%5Xi Intermediate Cup #2%1\nDriving License")
Text("XI INTERMEDIATE CUP #3 LICENSE")
Text("%2Survival Match%1\n%5Xi Intermediate Cup #3%1\nDriving License")
Text("S.G.M. ADVANCED CUP LICENSE")
Text("%2Survival Match%1\n%5S.G.M. Advanced Cup #3%1\nDriving License")
Text("S.G.M. ADVANCED CUP #2 LICENSE")
Text("%2Survival Match%1\n%5S.G.M. Advanced Cup #2%1\nDriving License")
Text("UNION SAVIOR SUPER CUP LICENSE")
Text("%2Survival Match%1\n%5Union Savior Super Cup%1\nDriving License")
Text("UNION SAVIOR SUPER CUP #2 LICENSE")
Text("%2Survival Match%1\n%5Union Savior Super Cup #2%1\nDriving License")
Text("UNION SAVIOR SUPER CUP #3 LICENSE")
Text("%2Survival Match%1\n%5Union Savior Super Cup #3%1\nDriving License")
Text("STORMZENDER EXTRA CUP LICENSE")
Text("%2Survival Match%1\n%5Stormzender Extra Cup%1\nDriving License")
Text("STORMZENDER EXTRA CUP #2 LICENSE")
Text("%2Survival Match%1\n%5Stormzender Extra Cup #2%1\nDriving License")
Text("STORMZENDER EXTRA CUP #3 LICENSE")
Text("%2Survival Match%1\n%5Stormzender Extra Cup #3%1\nDriving License")
Text("SUGO LEGEND CUP LICENSE")
Text("%2Survival Match%1\n%5Sugo Legend Cup #3%1\nDriving License")
Text("CF PRECIOUS CUP LICENSE")
Text("%2Survival Match%1\n%5Cyber Formula Precious Cup%1\nDriving License")
Text("CF PRECIOUS CUP #2 LICENSE")
Text("%2Survival Match%1\n%5Cyber Formula Precious Cup #2%1\nDriving License")
Text("P.P.P. INTERMEDIATE CUP LICENSE")
Text("%2Point Match%1\n%5P.P.P. Intermediate Cup%1\nDriving License")
Text("P.P.P. INTERMEDIATE CUP #2 LICENSE")
Text("%2Point Match%1\n%5P.P.P Intermediate Cup #2%1\nDriving License")
Text("P.P.P. INTERMEDIATE CUP #3 LICENSE")
Text("%2Point Match%1\n%5P.P.P. Intermediate Cup #3%1\nDriving License")
Text("KOLN ADVANCED CUP LICENSE")
Text("%2Point Match%1\n%5Koln Advanced Cup%1\nDriving License")
Text("KOLN ADVANCED CUP #2 LICENSE")
Text("%2Point Match%1\n%5Koln Advanced Cup #2%1\nDriving License")
Text("A.G.S SUPER CUP LICENSE")
Text("%2Point Match%1\n%5A.G.S. Super Cup%1\nDriving License")
Text("A.G.S. SUPER CUP #2 LICENSE")
Text("%2Point Match%1\n%5A.G.S. Super Cup #2%1\nDriving License")
Text("A.G.S. SUPER CUP #3 LICENSE")
Text("%2Point Match%1\n%2Survival Match%1\n the %5A.G.S. Super Cup #3%1")
Text("MISSING LINK EXTRA CUP LICENSE")
Text("%2Point Match%1\n%5Missing Link Extra Cup%1\nDriving License")
Text("MISSING LINK EXTRA CUP #2 LICENSE")
Text("%2Point Match%1\n%5Missing Link Extra Cup #2%1\nDriving License")
Text("MISSING LINK EXTRA CUP #3 LICENSE")
Text("%2Point Match%1\n%5Missing Link Extra Cup #3%1\nDriving License")
Text("AOI LEGEND CUP LICENSE")
Text("%2Point Match%1\n%5Aoi Legend Cup%1\nDriving License")
Text("CF UNLIMITED CUP LICENSE")
Text("%2Point Match%1\n%5Cyber Formula Unlimited Cup%1\nDriving License")
Text("CF UNLIMITED CUP #2 LICENSE")
Text("%2Point Match%1\n%5Cyber Formula Unlimited Cup #2%1\nDriving License")
Text("FICCY ADVANCED GPX LICENSE")
Text("%2Grand Prix%1\n%5Ficcy Advanced GPX%1\nDriving License")
Text("FICCY SUPER GPX LICENSE")
Text("%2Grand Prix%1\n%5Ficcy Super GPX%1\nDriving License")
Text("FICCY EXTRA GPX LICENSE")
Text("%2Grand Prix%1\n%5Ficcy Extra GPX%1\nDriving License")
Text("FICCY DREAM GPX LICENSE")
Text("%2Grand Prix%1\n%5Ficcy Dream GPX%1\nDriving License")
Text("FICCY ALL STAR GPX LICENSE")
Text("%2Survival Match%1\n%5Ficcy All Star GPX%1\nDriving License.")
Text("FICCY EXTREME GPX LICENSE")
Text("%2Survival Match%1\n%5Ficcy Extreme GPX%1\nDriving License.")
Text("CF INFINITY GPX LICENSE")
Text("%2Survival Match%1\n%5Cyber Formula Infinity GPX%1\nDriving License.")
Text("C.F. CARD COLLECTION VOL.1")
Text("Cyber Formula Card Collection Vol. 1\n(5 cards per pack)")
Text("C.F. CARD COLLECTION VOL.2")
Text("Cyber Formula Card Collection Vol. 2\n(5 cards per pack)")
Text("C.F. CARD COLLECTION VOL.3")
Text("Cyber Formula Card Collection Vol. 3\n(5 cards per pack)")
Text("C.F. CARD COLLECTION VOL.4")
Text("Cyber Formula Card Collection Vol. 4\n(5 cards per pack)")
Text("JUST A DROP IN THE OCEAN")
Text("BGM20\n%3Just a Drop in the Ocean%1")
Text("HEAD-ON CRUSH (HIGHER MIX)")
Text("BGM21\n%3Head-On Crush (Remix)%1")
Text("DISORDER (PRIMITIVE MIX)")
Text("BGM22\n%3Disorder (PRIMITIVE MIX)%1")
Text("AERO RAVE")
Text("BGM23\n%3Aero Rave%1")
Text("PRACTICE BATTLE")
Text("BGM24\n%3PRACTICE BATTLE%1")
Text("BGM25\n%3Destiny%1")
Text("SOUL TWINS (INSTRUMENTAL)")
Text("BGM26\n%3SOUL TWINS\n(Instrumental ver.)%1")
Text("IDENTITY CRISIS (INSTRUMENTAL)")
Text("BGM27\n%3IDENTITY CRISIS\n(Instrumental ver.)%1")
Text("ENDLESS FIELD")
Text("BGM28\n%3ENDLESS FIELD%1")
Text("FUTURE GPX")
Text("BGM29\n%3FUTURE GPX%1")
Text("CHALLENGER")
Text("BGM30\n%3CHALLENGER%1")
Text("TAMASHII")
Text("BGM31\n%3Soul%1")
Text("BGM32\n%3--%1") //Determination
Text("BGM33\n%3Challenge%1")
Text("BGM34\n%3Distrust%1")
