Text($001F3D40, "%1K.A.M. Tournament\n%5Difficulty: š%1")
Text("%1Nourish Xi Tournament\n%5Difficulty: šš%1")
Text("%1S.G.M. Tournament\n%5Difficulty: ššš%1")
Text("%1Union Savior Tournament\n%5Difficulty: šššš%1")
Text("%1Storm Zender Tournament\n%5Difficulty: ššššš%1")
Text("%1Sugo Tournament\n%5Difficulty: šššššš%1")
Text("%1Secret Tournament\n%5Difficulty: ššššššš%1")
Text("%1Secret Tournament\n%5Difficulty: šššššššš%1")
Text("%1Hollow Stag Tournament\n%5Difficulty: š%1")
Text("%1P.P.P. Tournament\n%5Difficulty: šš%1")
Text("%1Koh-i-Noor Tournament\n%5Difficulty: ššš%1")
Text("%1A.G.S. Tournament\n%5Difficulty: ššš%1")
Text("%1A.G.S. Tournament\n%5Difficulty: šššš%1")
Text("%1Missing Link Tournament\n%5Difficulty: ššššš%1")
Text("%1Aoi ZIP Tournament\n%5Difficulty: šššššš%1")

Text($001F4120, "Save the current game")
Text("To the Arcade menu.")
Text("To Course Select.")
Text("To Tournament Select.")

Text($001F4724, "Return to main menu.")

Text($001F4870, "%1\n%5Difficulty: š%1")
Text("%1Int Tournament (6 races)\n%5Difficulty: šš%1")
Text("%1Int Tournament (6 races)\n%5Difficulty: ššš%1")
Text("%1Adv Tournament (8 races)\n%5Difficulty: šššš%1")
Text("%1Adv Tournament (8 races)\n%5Difficulty: ššššš%1")
Text("%1Adv Tournament (8 races)\n%5Difficulty: šššššš%1")
Text("%1Mas Tournament (12 races)\n%5Difficulty: ššššššš%1")
Text("%1Mas Tournament (12 races)\n%5Difficulty: šššššššš%1")
Text("If you start a new grand prix,")
Text("your continue data will be erased.")
Text("Continue?")
Text("If you skip qualifying,")
Text("you will start from the back of the grid.")

//Text("Return to the main menu.")
//Text("Save to continue.")
